import type { Product } from './types'

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Cartões de Visita Premium',
    slug: 'cartoes-visita-premium',
    description: 'Cartões de visita em papel couché 300g com acabamento fosco. Impressão colorida frente e verso.',
    category: 'cartoes',
    price: 89.90,
    image_url: '',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '2',
    name: 'Banner 1x2m',
    slug: 'banner-1x2m',
    description: 'Banner em lona 440g com impressão digital de alta qualidade. Ideal para eventos e fachadas.',
    category: 'banners',
    price: 134.91,
    original_price: 149.90,
    discount_percent: 10,
    image_url: '',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '3',
    name: 'Adesivos Personalizados',
    slug: 'adesivos-personalizados',
    description: 'Adesivos em vinil com corte especial. Resistente à água e UV.',
    category: 'adesivos',
    price: 47.92,
    original_price: 59.90,
    discount_percent: 20,
    image_url: '',
    featured: true,
    created_at: new Date().toISOString(),
  },
  {
    id: '4',
    name: 'Flyers A5',
    slug: 'flyers-a5',
    description: 'Flyers coloridos em papel couché 150g. Perfeito para divulgação.',
    category: 'flyers',
    price: 79.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '5',
    name: 'Cartão de Visita Verniz Localizado',
    slug: 'cartao-verniz',
    description: 'Cartão premium com verniz localizado para destacar elementos do design.',
    category: 'cartoes',
    price: 129.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '6',
    name: 'Banner Roll-Up',
    slug: 'banner-rollup',
    description: 'Banner retrátil com estrutura em alumínio. Fácil montagem e transporte.',
    category: 'banners',
    price: 299.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '7',
    name: 'Adesivos Transparentes',
    slug: 'adesivos-transparentes',
    description: 'Adesivos em vinil transparente. Efeito premium para sua marca.',
    category: 'adesivos',
    price: 89.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '8',
    name: 'Folder A4',
    slug: 'folder-a4',
    description: 'Folder dobrado em papel couché 170g. Ideal para apresentações.',
    category: 'print',
    price: 99.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '9',
    name: 'Impressão A3 Colorida',
    slug: 'impressao-a3',
    description: 'Impressão colorida em papel couché 170g. Alta qualidade.',
    category: 'print',
    price: 12.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '10',
    name: 'Convites Personalizados',
    slug: 'convites',
    description: 'Convites em papel especial com acabamento premium. Perfeito para eventos.',
    category: 'print',
    price: 149.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '11',
    name: 'Fachada ACM',
    slug: 'fachada-acm',
    description: 'Placa em ACM com impressão digital. Durabilidade e qualidade.',
    category: 'banners',
    price: 599.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '12',
    name: 'Etiquetas Adesivas',
    slug: 'etiquetas',
    description: 'Etiquetas em papel adesivo. Diversos tamanhos e formatos.',
    category: 'adesivos',
    price: 49.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '13',
    name: 'Adesivos para Veículos',
    slug: 'adesivos-veiculos',
    description: 'Adesivos automotivos em vinil de alta qualidade. Resistente ao sol e chuva.',
    category: 'adesivos',
    price: 199.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '14',
    name: 'Banner X-Banner',
    slug: 'banner-x',
    description: 'Banner com estrutura em X. Leve e fácil de transportar.',
    category: 'banners',
    price: 189.90,
    image_url: '',
    created_at: new Date().toISOString(),
  },
  {
    id: '15',
    name: 'Impressão Offset',
    slug: 'impressao-offset',
    description: 'Impressão offset de alta qualidade. Ideal para grandes tiragens.',
    category: 'print',
    price: 0.50,
    image_url: '',
    created_at: new Date().toISOString(),
  },
]
