
'use client'

import Image from 'next/image'
import { useCallback, useEffect, useMemo, useState, type DragEvent } from 'react'
import { motion } from 'framer-motion'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { RefreshCcw, Save, Plus, X, Trash, Package, Edit2, GripVertical } from 'lucide-react'
import { z } from 'zod'

import { Button } from '@/components/admin/ui/button'
import { Input } from '@/components/admin/ui/input'
import { ToggleSwitch } from '@/components/admin/ui/toggle-switch'
import { Form, FormControl, FormDescription, FormField, FormItem, FormLabel, FormMessage } from '@/components/admin/ui/form'
import MediaPicker from '@/components/admin/ui/media-picker'
import { useToast } from '@/components/admin/ui/use-toast'
import { Modal } from '@/components/admin/ui/modal'
import CategoryProductsModal from '@/components/admin/categories/category-products-modal'
import { slugifyId } from '@/lib/content'
import type { ProductCategory } from '@/lib/types'
import type { UploadedImageMeta } from '@/lib/uploads'

const categoryFormSchema = z.object({
  name: z
    .string()
    .trim()
    .min(2, 'Nome deve ter pelo menos 2 caracteres'),
  slug: z
    .string()
    .trim()
    .min(2, 'Slug deve ter pelo menos 2 caracteres')
    .regex(/^[a-z0-9-]+$/, 'Use apenas letras minúsculas, números e hífens'),
  description: z
    .string()
    .trim()
    .max(300, 'Descrição pode ter no máximo 300 caracteres')
    .optional()
    .or(z.literal('')),
  sort_order: z.number().min(0, 'Ordem mínima é 0').max(999, 'Ordem máxima é 999'),
  active: z.boolean(),
  image_url: z.string().trim().url('Informe uma URL válida').optional().or(z.literal('')),
  storage_path: z.string().trim().optional().or(z.literal('')),
})

type CategoryFormValues = z.infer<typeof categoryFormSchema>

export default function CategoriesAdminPage() {
  const [categories, setCategories] = useState<ProductCategory[]>([])
  const [loading, setLoading] = useState(true)
  const [categoryImage, setCategoryImage] = useState<UploadedImageMeta | null>(null)
  const [editingId, setEditingId] = useState<string | null>(null)
  const [errorMessage, setErrorMessage] = useState<string | null>(null)
  const [selectedCategoryForProducts, setSelectedCategoryForProducts] = useState<ProductCategory | null>(null)
  const [isSlugEditable, setIsSlugEditable] = useState(false)
  const [slugManuallyEdited, setSlugManuallyEdited] = useState(false)
  const [categoryPendingRemoval, setCategoryPendingRemoval] = useState<ProductCategory | null>(null)
  const [deleting, setDeleting] = useState(false)
  const [draggedCategoryId, setDraggedCategoryId] = useState<string | null>(null)
  const [reordering, setReordering] = useState(false)
  const { toast } = useToast()

  const form = useForm<CategoryFormValues>({
    resolver: zodResolver(categoryFormSchema),
    defaultValues: {
      name: '',
      slug: '',
      description: '',
      sort_order: 1,
      active: true,
      image_url: '',
      storage_path: '',
    },
  })
  const {
    control,
    handleSubmit,
    register,
    reset,
    setValue,
    watch,
    formState: { errors, isSubmitting },
  } = form

  const watchedName = watch('name')
  const watchedSlug = watch('slug')
  const watchedImageUrl = watch('image_url')
  const watchedDescription = watch('description')
  const watchedActive = watch('active')
  const activeCount = categories.filter((category) => category.active).length
  const inactiveCount = Math.max(0, categories.length - activeCount)
  const orderedCategories = useMemo(
    () => [...categories].sort((a, b) => (a.sort_order ?? 0) - (b.sort_order ?? 0)),
    [categories],
  )

  const loadCategories = useCallback(async () => {
    setLoading(true)
    try {
      const response = await fetch('/api/admin/categories')
      if (response.ok) {
        const payload = await response.json()
        setCategories(payload.categories || [])
      } else {
        throw new Error('Erro ao buscar categorias')
      }
    } catch (error) {
      console.error(error)
      setErrorMessage('Nao foi possivel carregar as categorias.')
      toast({
        variant: 'destructive',
        title: 'Falha ao carregar',
        description: 'Nao foi possivel carregar as categorias.',
      })
    } finally {
      setLoading(false)
    }
  }, [toast])

  useEffect(() => {
    loadCategories()
  }, [loadCategories])

useEffect(() => {
  if (!slugManuallyEdited && !editingId) {
    const autogenerated = slugifyId(watchedName || '')
    setValue('slug', autogenerated)
  }
}, [watchedName, slugManuallyEdited, editingId, setValue])

useEffect(() => {
  if (!editingId) {
    setValue('sort_order', categories.length + 1)
  }
}, [categories.length, editingId, setValue])

  useEffect(() => {
    if (!watchedImageUrl && categoryImage) {
      setCategoryImage(null)
    }
  }, [watchedImageUrl, categoryImage])

  const handleCategoryImageChange = (image: UploadedImageMeta | null) => {
    setCategoryImage(image)
    setValue('image_url', image?.url ?? '', { shouldDirty: true })
    setValue('storage_path', image?.storagePath ?? '', { shouldDirty: true })
  }

  const resetForm = () => {
    setEditingId(null)
    setCategoryImage(null)
    setIsSlugEditable(false)
    setSlugManuallyEdited(false)
    reset({
      name: '',
      slug: '',
      description: '',
      sort_order: categories.length + 1,
      active: true,
      image_url: '',
      storage_path: '',
    })
  }

  const handleEdit = (category: ProductCategory) => {
    setEditingId(category.id)
    setIsSlugEditable(false)
    setSlugManuallyEdited(true)
    reset({
      name: category.name,
      slug: category.id,
      description: category.description || '',
      sort_order: category.sort_order ?? 1,
      active: category.active ?? true,
      image_url: category.image_url || '',
      storage_path: category.storage_path || '',
    })

    setCategoryImage(
      category.image_url
        ? { url: category.image_url, storagePath: category.storage_path || '' }
        : null
    )
  }

  const onSubmit = async (values: CategoryFormValues) => {
    setErrorMessage(null)

    try {
      const payload = {
        id: values.slug,
        name: values.name,
        description: values.description?.trim() ? values.description.trim() : undefined,
        image_url: categoryImage?.url || values.image_url || undefined,
        storage_path: categoryImage?.storagePath || values.storage_path || undefined,
        sort_order: values.sort_order,
        active: values.active,
      }

      const endpoint = editingId ? `/api/admin/categories/${editingId}` : '/api/admin/categories'
      const method = editingId ? 'PUT' : 'POST'

      const response = await fetch(endpoint, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(payload),
      })

      if (!response.ok) {
        const data = await response.json().catch(() => ({}))
        throw new Error(data.error || 'Erro ao salvar categoria')
      }

      const data = await response.json()
      
      resetForm()
      await loadCategories()

      toast({
        variant: 'success',
        title: editingId ? 'Categoria atualizada' : 'Categoria criada',
        description: `Categoria "${data.category?.name || values.name}" salva com sucesso.`,
      })
    } catch (error) {
      console.error(error)
      setErrorMessage(
        error instanceof Error ? error.message : 'Erro inesperado ao salvar categoria.'
      )
      toast({
        variant: 'destructive',
        title: 'Falha ao salvar',
        description:
          error instanceof Error ? error.message : 'Erro inesperado ao salvar categoria.',
      })
    }
  }

  const handleToggleActive = async (category: ProductCategory) => {
    try {
      const response = await fetch(`/api/admin/categories/${category.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ active: !category.active }),
      })

      if (!response.ok) {
        throw new Error('Erro ao atualizar categoria')
      }

      await loadCategories()
      toast({
        variant: 'success',
        title: category.active ? 'Categoria desativada' : 'Categoria ativada',
        description: `O status de "${category.name}" foi atualizado.`,
      })
    } catch (error) {
      console.error(error)
      toast({
        variant: 'destructive',
        title: 'Falha ao atualizar',
        description: 'Nao foi possivel atualizar a categoria.',
      })
    }
  }

  const requestDeleteCategory = (category: ProductCategory) => {
    setCategoryPendingRemoval(category)
  }

  const handleCancelDelete = () => {
    if (deleting) return
    setCategoryPendingRemoval(null)
  }

  const handleConfirmDelete = async () => {
    if (!categoryPendingRemoval) return
    const category = categoryPendingRemoval
    setDeleting(true)

    const previousCategories = [...categories]
    setCategories((prev) => prev.filter((cat) => cat.id !== category.id))

    try {
      const response = await fetch(`/api/admin/categories/${category.id}`, {
        method: 'DELETE',
      })

      if (!response.ok) {
        const data = await response.json().catch(() => ({}))
        throw new Error(data.error || 'Erro ao remover categoria')
      }

      await loadCategories()
      toast({
        variant: 'success',
        title: 'Categoria removida',
        description: `"${category.name}" foi removida.`,
      })
    } catch (error) {
      console.error(error)
      setCategories(previousCategories)
      toast({
        variant: 'destructive',
        title: 'Falha ao remover',
        description:
          error instanceof Error ? error.message : 'Nao foi possivel remover a categoria.',
      })
    } finally {
      setDeleting(false)
      setCategoryPendingRemoval(null)
    }
  }

  const handleDragStart = (event: DragEvent<HTMLButtonElement>, categoryId: string) => {
    event.stopPropagation()
    event.dataTransfer.effectAllowed = 'move'
    event.dataTransfer.setData('text/plain', categoryId)
    setDraggedCategoryId(categoryId)
  }

  const handleDragOver = (event: DragEvent<HTMLTableRowElement>) => {
    event.preventDefault()
  }

  const handleDrop = async (event: DragEvent<HTMLTableRowElement>, targetId: string) => {
    event.preventDefault()
    if (!draggedCategoryId || draggedCategoryId === targetId) {
      setDraggedCategoryId(null)
      return
    }

    const fromIndex = orderedCategories.findIndex((category) => category.id === draggedCategoryId)
    const toIndex = orderedCategories.findIndex((category) => category.id === targetId)

    if (fromIndex === -1 || toIndex === -1) {
      setDraggedCategoryId(null)
      return
    }

    const reordered = [...orderedCategories]
    const [moved] = reordered.splice(fromIndex, 1)
    if (!moved) {
      setDraggedCategoryId(null)
      return
    }
    reordered.splice(toIndex, 0, moved)

    const normalized = reordered.map((category, index) => ({
      ...category,
      sort_order: index + 1,
    }))

    setCategories(normalized)
    setDraggedCategoryId(null)
    setReordering(true)

    try {
      const response = await fetch('/api/admin/categories/reorder', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          items: normalized.map((category, index) => ({
            id: category.id,
            sort_order: index + 1,
          })),
        }),
      })

      if (!response.ok) {
        const payload = await response.json().catch(() => ({}))
        throw new Error(payload.error || 'Não foi possível salvar a nova ordem.')
      }

      toast({
        variant: 'success',
        title: 'Ordem atualizada',
        description: 'A nova ordem das categorias foi salva.',
      })
      await loadCategories()
    } catch (error) {
      console.error(error)
      toast({
        variant: 'destructive',
        title: 'Erro ao reordenar categorias',
        description: error instanceof Error ? error.message : 'Tente novamente em instantes.',
      })
      await loadCategories()
    } finally {
      setReordering(false)
    }
  }

  return (
    <div className="p-6 space-y-8">
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <p className="text-sm text-[#6E6E73]">Administração &gt; Conteúdo base</p>
          <h1 className="text-3xl font-normal text-[#1D1D1F]">Categorias da homepage</h1>
          <p className="text-[#6E6E73] mt-2 max-w-2xl">
            Gerencie as categorias exibidas na homepage. Crie, edite e organize o conteúdo apresentado aos clientes.
          </p>
        </div>
        <div className="flex gap-3">
          <Button onClick={loadCategories} variant="ghost" icon={<RefreshCcw className="w-4 h-4" />}>
            Atualizar
          </Button>
        </div>
      </div>

      {errorMessage && (
        <div className="bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-xl">
          {errorMessage}
        </div>
      )}

      <div className="grid gap-6 md:grid-cols-3">
        <div className="bg-white border border-[#E5E5EA] rounded-xl p-4">
          <p className="text-sm text-[#6E6E73]">Total de categorias</p>
          <p className="text-3xl font-normal text-[#1D1D1F]">
            {categories.length}
            {loading && <span className="text-sm text-[#6E6E73] ml-1">Carregando...</span>}
          </p>
        </div>
        <div className="bg-white border border-[#E5E5EA] rounded-xl p-4">
          <p className="text-sm text-[#6E6E73]">Ativas</p>
          <p className="text-3xl font-normal text-[#1D1D1F]">{activeCount}</p>
        </div>
        <div className="bg-white border border-[#E5E5EA] rounded-xl p-4">
          <p className="text-sm text-[#6E6E73]">Inativas</p>
          <p className="text-3xl font-normal text-[#1D1D1F]">{inactiveCount}</p>
        </div>
      </div>

      <Form {...form}>
        <form onSubmit={handleSubmit(onSubmit)} className="space-y-6">
          <div className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(320px,1fr)]">
            <motion.div
              initial={{ opacity: 0, y: 16 }}
              animate={{ opacity: 1, y: 0 }}
              className="bg-white border border-[#E5E5EA] rounded-2xl p-6 space-y-6"
            >
              <div className="flex flex-col gap-1 sm:flex-row sm:items-center sm:justify-between">
                <div>
                  <p className="text-sm text-[#6E6E73]">
                    {editingId ? 'Editar categoria' : 'Adicionar nova categoria'}
                  </p>
                  <h2 className="text-2xl font-normal text-[#1D1D1F]">
                    {editingId ? `Atualizando ${watchedName || editingId}` : 'Nova categoria'}
                  </h2>
                </div>
                {editingId && (
                  <Button type="button" variant="ghost" icon={<X className="w-4 h-4" />} onClick={resetForm}>
                    Cancelar
                  </Button>
                )}
              </div>

              <div className="grid gap-5">
                <FormField
                  control={control}
                  name="name"
                  render={({ field }) => {
                    const inputId = 'category-name'
                    return (
                      <FormItem>
                        <FormLabel htmlFor={inputId}>Nome</FormLabel>
                        <FormControl>
                          <Input
                            id={inputId}
                            required
                            placeholder="Ex.: Cartões de Visita"
                            {...field}
                            error={errors.name?.message}
                          />
                        </FormControl>
                      </FormItem>
                    )
                  }}
                />

                <div className="space-y-2">
                  <div className="flex flex-col gap-3 sm:flex-row sm:items-start">
                    <div className="flex-1">
                      <Input
                        label="Slug/ID"
                        placeholder="cartoes"
                        {...register('slug', {
                          onChange: () => setSlugManuallyEdited(true),
                          validate: (value) => {
                            const trimmed = (value || '').trim()
                            if (!trimmed) return 'Slug é obrigatório'
                            const exists = categories.some((cat) => cat.id === trimmed)
                            if (exists && editingId && trimmed === editingId) {
                              return true
                            }
                            if (exists) {
                              return 'Este slug já está em uso'
                            }
                            return true
                          },
                        })}
                        readOnly={!isSlugEditable}
                        helper={
                          isSlugEditable
                            ? 'Use apenas letras minúsculas, números e hífens.'
                            : 'Slug gerado automaticamente a partir do nome.'
                        }
                        error={errors.slug?.message}
                      />
                    </div>
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      icon={<Edit2 className="w-4 h-4" />}
                      onClick={() => {
                        setIsSlugEditable((prev) => !prev)
                        setSlugManuallyEdited(true)
                      }}
                    >
                      {isSlugEditable ? 'Bloquear' : 'Editar slug'}
                    </Button>
                  </div>
                  <p className="text-xs text-[#6E6E73]">ID atual: {watchedSlug || '—'}</p>
                </div>

                <FormField
                  control={control}
                  name="sort_order"
                  render={({ field }) => (
                    <FormControl>
                      <input type="hidden" value={field.value ?? 0} readOnly ref={field.ref} />
                    </FormControl>
                  )}
                />

                <FormField
                  control={control}
                  name="description"
                  render={({ field }) => {
                    const inputId = 'category-description'
                    return (
                      <FormItem>
                        <FormLabel htmlFor={inputId}>Descrição</FormLabel>
                        <FormControl>
                          <textarea
                            id={inputId}
                            {...field}
                            rows={3}
                            className="w-full rounded-xl border border-[#D2D2D7] px-4 py-3 text-sm focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#007AFF]"
                          />
                        </FormControl>
                        <FormDescription>Resumo curto exibido na homepage.</FormDescription>
                        <FormMessage />
                      </FormItem>
                    )
                  }}
                />
              </div>
            </motion.div>

            <aside className="space-y-6 lg:sticky lg:top-6">
              <motion.div
                initial={{ opacity: 0, x: 16 }}
                animate={{ opacity: 1, x: 0 }}
                className="bg-white border border-[#E5E5EA] rounded-2xl p-6 space-y-5"
              >
                <div className="space-y-1">
                  <p className="text-xs font-semibold text-[#6E6E73] tracking-[0.2em]">
                    CONTROLE
                  </p>
                  <h3 className="text-lg font-medium text-[#1D1D1F]">Status e conteúdo</h3>
                </div>

                <MediaPicker
                  label="Imagem da categoria"
                  value={categoryImage}
                  onChange={(v) => handleCategoryImageChange(v as UploadedImageMeta | null)}
                  bucket="media"
                  entity="categories"
                  entityId={watchedSlug}
                  helperText="Após definir o slug a imagem será salva em media/categories/<slug>/."
                />

                <FormField
                  control={control}
                  name="active"
                  render={({ field }) => (
                    <FormItem>
                      <FormControl>
                        <ToggleSwitch
                          checked={field.value}
                          label={field.value ? 'Categoria ativa' : 'Categoria inativa'}
                          description="Categorias inativas não aparecem na homepage."
                          onClick={() => field.onChange(!field.value)}
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />

                <div className="flex flex-col gap-3 pt-2">
                  <Button
                    type="submit"
                    loading={isSubmitting}
                    icon={editingId ? <Save className="w-4 h-4" /> : <Plus className="w-4 h-4" />}
                  >
                    {editingId ? 'Atualizar categoria' : 'Criar categoria'}
                  </Button>
                  {editingId && (
                    <Button type="button" variant="secondary" onClick={resetForm}>
                      Criar nova categoria
                    </Button>
                  )}
                </div>
              </motion.div>

              <CategoryPreviewCard
                name={watchedName}
                description={watchedDescription}
                imageUrl={categoryImage?.url || watchedImageUrl}
                slug={watchedSlug}
                active={watchedActive}
              />

            </aside>
          </div>
        </form>
      </Form>

      <section className="bg-white border border-[#E5E5EA] rounded-2xl p-6 space-y-4">
        <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-3">
          <div>
            <h3 className="text-lg font-normal text-[#1D1D1F]">Categorias cadastradas</h3>
            <p className="text-sm text-[#6E6E73]">
              {categories.length === 0
                ? 'Nenhuma categoria criada ainda.'
                : `Você tem ${activeCount} categoria(s) ativa(s) visíveis na homepage.`}
            </p>
            {categories.length > 0 && (
              <p className="text-xs text-[#6E6E73] mt-1">
                Defina a ordem arrastando as categorias na lista abaixo. A posição é salva automaticamente.
              </p>
            )}
          </div>
          {reordering && (
            <span className="text-xs text-[#6E6E73]">Salvando nova ordem…</span>
          )}
        </div>

        {loading ? (
          <div className="space-y-2">
            {[...Array(4)].map((_, index) => (
              <div key={index} className="h-14 w-full rounded-xl bg-[#F5F5F5] animate-pulse" />
            ))}
          </div>
        ) : categories.length === 0 ? (
          <div className="text-center text-[#6E6E73] py-12 border border-dashed border-[#E5E5EA] rounded-xl">
            Nenhuma categoria cadastrada.
          </div>
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-[#6E6E73] border-b border-[#F2F2F7]">
                  <th className="w-10 py-3" />
                  <th className="py-3">Nome</th>
                  <th className="py-3">Slug</th>
                  <th className="py-3">Status</th>
                  <th className="py-3 text-right">Ações</th>
                </tr>
              </thead>
              <tbody>
                {orderedCategories.map((category) => (
                  <tr
                    key={category.id}
                    onDragOver={handleDragOver}
                    onDrop={(event) => handleDrop(event, category.id)}
                    className={`border-b border-[#F2F2F7] last:border-0 ${
                      draggedCategoryId === category.id ? 'opacity-60' : ''
                    }`}
                  >
                    <td className="py-3 pr-2 align-middle text-[#6E6E73]">
                      <button
                        type="button"
                        className="cursor-grab text-[#6E6E73] hover:text-[#1D1D1F]"
                        aria-label="Arrastar categoria"
                        draggable
                        onDragStart={(event) => handleDragStart(event, category.id)}
                        onDragEnd={() => setDraggedCategoryId(null)}
                      >
                        <GripVertical className="w-4 h-4" />
                      </button>
                    </td>
                    <td className="py-3 font-medium text-[#1D1D1F]">{category.name}</td>
                    <td className="py-3 text-[#6E6E73]">{category.id}</td>
                    <td className="py-3">
                      <span
                        className={`inline-flex rounded-full px-2 py-0.5 text-xs font-medium ${
                          category.active ? 'bg-green-100 text-green-700' : 'bg-gray-200 text-gray-600'
                        }`}
                      >
                        {category.active ? 'Ativa' : 'Inativa'}
                      </span>
                    </td>
                    <td className="py-3">
                      <div className="flex items-center justify-end gap-2">
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => setSelectedCategoryForProducts(category)}
                          icon={<Package className="w-4 h-4" />}
                          title="Gerenciar produtos vinculados"
                        >
                          Produtos
                        </Button>
                        <Button
                          variant="secondary"
                          size="sm"
                          onClick={() => handleToggleActive(category)}
                        >
                          {category.active ? 'Desativar' : 'Ativar'}
                        </Button>
                        <Button variant="ghost" size="sm" onClick={() => handleEdit(category)}>
                          Editar
                        </Button>
                        <Button
                          variant="ghost"
                          size="sm"
                          onClick={() => requestDeleteCategory(category)}
                          icon={<Trash className="w-4 h-4" />}
                        >
                          Remover
                        </Button>
                      </div>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>

      {/* Modal de produtos vinculados */}
      {selectedCategoryForProducts && (
        <CategoryProductsModal
          category={selectedCategoryForProducts}
          allCategories={categories}
          isOpen={true}
          onClose={() => setSelectedCategoryForProducts(null)}
          onProductsMoved={() => {
            // Recarregar categorias após mover produtos (pode afetar contagens)
            loadCategories()
          }}
        />
      )}

      <Modal
        isOpen={Boolean(categoryPendingRemoval)}
        onClose={handleCancelDelete}
        title="Remover categoria"
        description={
          categoryPendingRemoval
            ? `Tem certeza de que deseja remover "${categoryPendingRemoval.name}"?`
            : undefined
        }
        size="sm"
      >
        <p className="text-sm text-[#6E6E73]">
          Esta ação é permanente e remove a categoria da homepage. Os produtos associados não serão deletados.
        </p>

        <div className="mt-6 flex flex-col gap-3 sm:flex-row">
          <Button variant="ghost" onClick={handleCancelDelete} disabled={deleting}>
            Cancelar
          </Button>
          <Button
            variant="destructive"
            icon={<Trash className="w-4 h-4" />}
            onClick={handleConfirmDelete}
            loading={deleting}
          >
            Remover categoria
          </Button>
        </div>
      </Modal>
    </div>
  )
}

interface CategoryPreviewProps {
  name?: string
  description?: string
  imageUrl?: string
  slug?: string
  active?: boolean
}

function CategoryPreviewCard({
  name,
  description,
  imageUrl,
  slug,
  active,
}: CategoryPreviewProps) {
  const displayName = name?.trim() || 'Nome da categoria'
  const displayDescription = description?.trim() || 'Descrição breve da categoria'

  return (
    <motion.div
      initial={{ opacity: 0, x: 16 }}
      animate={{ opacity: 1, x: 0 }}
      className="bg-white border border-[#E5E5EA] rounded-2xl p-6 space-y-4"
    >
      <div className="flex items-center justify-between">
        <div>
          <p className="text-xs font-semibold text-[#6E6E73] tracking-[0.2em]">PREVIEW</p>
          <h3 className="text-lg font-medium text-[#1D1D1F]">Visual na homepage</h3>
          <p className="text-xs text-[#6E6E73]">Pré-visualização fiel do card exibido na vitrine.</p>
        </div>
        <span
          className={`text-xs font-medium px-3 py-1 rounded-full ${
            active ? 'bg-green-100 text-green-700' : 'bg-gray-200 text-gray-600'
          }`}
        >
          {active ? 'Ativa na homepage' : 'Inativa'}
        </span>
      </div>

      <div className="flex flex-col items-center text-center gap-4">
        <div
          className="relative aspect-square w-36 rounded-full overflow-hidden bg-[#F5F5F7] dark:bg-black border border-[#E5E5EA] shadow-sm flex items-center justify-center"
        >
          {imageUrl ? (
            <Image
              src={imageUrl}
              alt={displayName}
              fill
              sizes="144px"
              className="object-cover"
            />
          ) : (
            <div className="absolute inset-0 flex flex-col items-center justify-center p-3 text-center">
              <p className="text-[11px] font-semibold text-[#6E6E73]">300 x 300</p>
              <p className="text-[10px] text-[#86868B] mt-1">pixels</p>
            </div>
          )}
        </div>

        <div>
          <p className="text-[10px] uppercase tracking-widest text-[#6E6E73] mb-1">
            /produtos?category={slug || 'slug'}
          </p>
          <h4 className="text-base font-medium text-[#1D1D1F] mb-0.5">{displayName}</h4>
          <p className="text-xs text-[#6E6E73]">{displayDescription}</p>
        </div>
      </div>
    </motion.div>
  )
}
